# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zhangqingdong.cn
date_format: "ordinal"
title: Never Bug End.
subtitle: "Stay hungry, Stay foolish."
description: "冬青的自留地"
keywords: 冬青, Qingdong, copyboy, copy_boy
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Qingdong Zhang
organization: 
organization_url: 
github_username: copyboy
location: Wuhan, China
email: copy_boy@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: copyboy/copyboy.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: copyboy
    repo: copyboy.github.io
    oauth:
        client_id: 0dad65920db919b3619f
        client_secret: 0f4d746b28a65cb2ec042ecd08c3280357671d1b
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: copyboy
    repo: copyboy.github.io
    clientID: 0dad65920db919b3619f
    clientSecret: 0f4d746b28a65cb2ec042ecd08c3280357671d1b
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
